### PR TITLE
Make `Selector.instance` work on iOS

### LINKED ISSUE #663: Webview interaction - selecting correct element when Selector applies to multiple elements
Let's assume the following login form:
Zrzut ekranu 2022-12-5 o 13 02 44

My app opens it in a web view, and I want to put some login and password and tap the "Log in" button. I use the following code:

```dart
await $.native.enterTextByIndex('some_login', index: 0);
await $.native.enterTextByIndex('some_password', index: 1);
await $.native.tap(Selector(text: 'Log in'));
```

Entering the text works like a charm, but the `tap()` command selects the header above the fields instead of the button. I tried with `className: 'button'`, `'className: 'Button'` (inspired by the [article on Medium](https://medium.com/azimolabs/android-webview-automation-testing-6311df8fe42e)), but it couldn't find such element. I also tried playing with the `instance` field, but I only got `IllegalArgumentException` with a message saying, that `instance` isn't supported.

Is there a way to select the button in such case?

### PR DESCRIPTION
**Pull request by bartekpacia**
This PR fixes #663 (the iOS part of it).

## Demo

Uses the [Landmarks app](https://github.com/bartekpacia/Landmarks) on [this commit](https://github.com/bartekpacia/Landmarks/commit/5021628ef5d03c471514d00ca9c90f5a80a2240a).

### tap()

```dart
// integration_test/internal/tap_test.dart
void main() {
  const appId = 'pl.baftek.Landmarks';

  patrol(
    'internal test',
    ($) async {
      await createApp($);

      await $.native.openApp(appId: appId);

      final turtleRock = Selector(text: 'Turtle Rock');
      final back = Selector(text: 'Landmarks');

      await $.native.tap(turtleRock, appId: appId);
      await $.native.tap(back, appId: appId);
      await $.native.tap(turtleRock..instance = 1, appId: appId);
      await $.native.tap(back, appId: appId);
    },
  );
}
```

https://github.com/leancodepl/patrol/assets/40357511/b3ab5a18-76ad-4ad2-8c0f-283264064467

### enterText()

```dart
// integration_test/internal/enter_text_test.dart
void main() {
  const appId = 'pl.baftek.Landmarks';

  patrol(
    'internal test',
    ($) async {
      await createApp($);

      await $.native.openApp(appId: appId);

      final username = Selector(text: 'username');

      // Old way – use enterTextByIndex
      /*
      await $.native.enterTextByIndex('My username', index: 0, appId: appId);
      await $.native.enterTextByIndex(
        'My username again!',
        index: 1,
        appId: appId,
      );
      */

      // New way - use Selector.instance
      await $.native.enterText(username, text: 'My username', appId: appId);
      await $.native.enterText(
        username..instance = 1,
        text: 'Username again',
        appId: appId,
      );
      await $.native.tap(
        Selector(text: 'Landmarks', instance: 2),
        appId: appId,
      );
    },
  );
}

```

https://github.com/leancodepl/patrol/assets/40357511/63b69ed7-a35f-44b2-a24b-589fb5a38ecf

---

These tests should be added as part of #1551.

### CODE REVIEW

File: packages/patrol/example/integration_test/webview_stackoverflow_test.dart [hunk 1]
```diff
@@ -17,17 +17,9 @@ void main() {
 
       await $.pump(Duration(seconds: 2));
 
-      // bug: using `Email` and `Password` selectors doesn't work
-      await $.native.enterTextByIndex(
-        'test@leancode.pl',
-        index: 0,
-        keyboardBehavior: KeyboardBehavior.showAndDismiss,
```
Comment (bartekpacia) [inline packages/patrol/example/integration_test/webview_stackoverflow_test.dart:24]: this is the default
