### PR TITLE
Change java path parsing

### LINKED ISSUE #2288: Can't build a test when Java path is different than the one from Android Studio
Building a test hangs on the `./gradlew...` command due to wrong parsing of java path obtained from `flutter doctor -v`.

### PR DESCRIPTION
**Pull request by pdenert**
fix #2288

### CODE REVIEW

File: packages/patrol_cli/lib/src/android/android_test_backend.dart [hunk 1]
```diff
@@ -128,13 +128,14 @@ class AndroidTestBackend {
         (line) async {
```
Comment (gogolon) [inline packages/patrol_cli/lib/src/android/android_test_backend.dart:128]: shouldn't we pass the entire flutter command here and invoke it along with its arguments to avoid the same problem that was in #2320?

Comment (gogolon) [reply packages/patrol_cli/lib/src/android/android_test_backend.dart:128]: I also see we do the same thing in `buildApkConfigOnly`

File: packages/patrol_cli/lib/src/android/android_test_backend.dart [hunk 2]
```diff
@@ -128,13 +128,14 @@ class AndroidTestBackend {
...
               javaCompleterPath.isCompleted == false) {
-            final path = line
-                .replaceAll('• Java binary at:', '')
-                .replaceAll(
-                  _platform.isWindows ? r'\bin\java' : '/bin/java',
-                  '',
-                )
-                .trim();
+            var path = line.replaceAll('• Java binary at:', '').trim();
+            if (path != '/usr/bin/java') {
```
Comment (gogolon) [inline packages/patrol_cli/lib/src/android/android_test_backend.dart:132]: i think a comment explaining this special case would be nice

**Review by piotruela — APPROVED** [review]

**Review by gogolon — APPROVED** [review]

**Review by gogolon — APPROVED** [review]
