### PR TITLE
Fix/scrolling rework

### LINKED ISSUE #1323: Rework of scrolling methods
We decided to change implementation of scrolling methods, to make them usable in more scenarios.

How it works now:

- scrolling can be performed only on a widget, that is of type `Scrollable`. That blocks usage of `scrollTo()` (and similar) on widgets do have custom gesture handling, but do not implement `Scrollable`.
- `Scrollable` that we want to scroll has to be found and has to be visible (more specifically - [hitTestable](https://api.flutter.dev/flutter/flutter_test/Finder/hitTestable.html)). There are some scenarios in which it doesn't work, because the desired `Scrollable` seems to be not hitTestable (though it is visible to the user).
- the actual dragging is implemented in the [`drag()` method from `flutter_test`](https://api.flutter.dev/flutter/flutter_test/WidgetController/drag.html). This causes very fast scrolling on `Scrollable`s with some non-standard scroll physics, which results in scrolling too far to find the widget we're looking for.

We would like:

- to be independent of what type the widget being scrolled is. `drag()` method can scroll any widget, though in some situations just nothing happens. We want to enable scrolling all widgets, including custom widgets, not only `Scrollable`.
- to perform dragging more slowly (which would be configurable) - to prevent from scrolling too far when there are some custom scroll physics.
- to enable usage of different pumping methods between drags.

### PR DESCRIPTION
**Pull request by jBorkowska**
This PR resolves #1323

### CODE REVIEW

File: packages/patrol/lib/src/custom_finders/patrol_tester.dart [hunk 1]
```diff
@@ -509,21 +566,31 @@ class PatrolTester {
     required Finder finder,
     Finder? scrollable,
     double delta = defaultScrollDelta,
+    AxisDirection? scrollDirection,
     int maxScrolls = defaultScrollMaxIteration,
     Duration duration = const Duration(milliseconds: 50),
-    bool? andSettle,
+    @Deprecated('Use settleBeahvior argument instead') bool? andSettle,
```
Comment (bartekpacia) [inline packages/patrol/lib/src/custom_finders/patrol_tester.dart:572]: typo (here and in other places)

**Comment by bartekpacia** [comment]
Let's add a link to the issue in the PR description @jBorkowska

File: packages/patrol/lib/src/custom_finders/patrol_tester.dart [hunk 2]
```diff
@@ -463,15 +463,15 @@ class PatrolTester {
     required Offset moveStep,
     int maxIteration = defaultScrollMaxIteration,
     Duration duration = const Duration(milliseconds: 50),
-    Duration dragDuration = const Duration(milliseconds: 1000),
+    Duration dragDuration = const Duration(milliseconds: 2000),
```
Comment (bartekpacia) [inline packages/patrol/lib/src/custom_finders/patrol_tester.dart:466]: `seconds: 2`

File: docs/finders/advanced.mdx [hunk 3]
```diff
@@ -136,8 +136,9 @@ await $('Delete account').scrollTo().tap();
 
 And here's how `scrollTo()` works:
 
-1. Waits for at least 1 [Scrollable] widget to become visible
-2. Scrolls this `Scrollable` widget in its scrolling direction until the target
+1. Waits for at least 1 [Scrollable] widget (or whatever you provided in 
+   `view` argument) to become visible
+2. Scrolls this widget in its scrolling direction until the target
```
Comment (bartekpacia) [inline docs/finders/advanced.mdx:141]: Is this true?

Comment (jBorkowska) [reply docs/finders/advanced.mdx:141]: Yeah, why?

Comment (bartekpacia) [reply docs/finders/advanced.mdx:141]: > Scrolls this widget **in its scrolling direction** until the target

I thought that `scrollTo()` no longer infers the direction automatically. I recall we talked about it some time ago. But I might just not remember correctly.

Comment (bartekpacia) [reply docs/finders/advanced.mdx:141]: Ah, okay - that's awesome.

File: packages/patrol/lib/src/custom_finders/patrol_tester.dart [hunk 4]
```diff
@@ -401,56 +401,71 @@ class PatrolTester {
...
-        settlePolicy: settlePolicy,
-      );
-      await _performPump(
-        settlePolicy: settle,
-        settleTimeout: config.settleTimeout,
-      );
+      if (iterationsLeft <= 0) {
+        throw WaitUntilExistsTimeoutException(
+          finder: finder,
+          // TODO: set reasonable duration
```
Comment (bartekpacia) [inline packages/patrol/lib/src/custom_finders/patrol_tester.dart:465]: 👀

File: packages/patrol/lib/src/custom_finders/patrol_tester.dart [hunk 5]
```diff
@@ -459,85 +474,101 @@ class PatrolTester {
...
-  ///    situations when [finder] finds more than 1 visible widget
+  ///  * if the [finder] finder finds more than 1 widget, it scrolls to the
+  ///    first one instead of throwing a [StateError]
+  ///
+  ///  * can drag any widget, not only a [Scrollable]
+  ///
+  ///  * performed drag is slower (it takes some time to performe dragging
+  ///    gesture, half a second by default)
+  ///
+  ///  * you can configure, which version of pumping is performed between
```
Comment (bartekpacia) [inline packages/patrol/lib/src/custom_finders/patrol_tester.dart:496]: performe -> perform

File: packages/patrol/lib/src/custom_finders/patrol_tester.dart [hunk 6]
```diff
@@ -459,85 +474,101 @@ class PatrolTester {
...
   ///
-  ///  * uses [WidgetController.firstElement] instead of
-  ///    [WidgetController.element], which avoids [StateError] being thrown in
-  ///    situations when [finder] finds more than 1 visible widget
+  ///  * if the [finder] finder finds more than 1 widget, it scrolls to the
+  ///    first one instead of throwing a [StateError]
+  ///
+  ///  * can drag any widget, not only a [Scrollable]
+  ///
+  ///  * performed drag is slower (it takes some time to performe dragging
```
Comment (bartekpacia) [inline packages/patrol/lib/src/custom_finders/patrol_tester.dart:493]: performe -> perform

File: packages/patrol/test/patrol_tester_test.dart [hunk 7]
```diff
@@ -538,7 +540,7 @@ void main() {
                     ),
                   ),
                   SingleChildScrollView(
-                    scrollDirection: Axis.horizontal,
+                    //scrollDirection: Axis.horizontal,
```
Comment (bartekpacia) [inline packages/patrol/test/patrol_tester_test.dart:543]: What's this?

**Review by bartekpacia — APPROVED** [review]

File: packages/patrol/lib/src/custom_finders/patrol_tester.dart (hunk 4 above)
Comment (jBorkowska) [reply packages/patrol/lib/src/custom_finders/patrol_tester.dart:465]: It's because I couldn't figure out what we should log here, bc we weren't waiting explicitly. And I still don't know what to put here.

Maybe we should implement separate exception for this situation.
