### PR TITLE
Fix granting iOS permissions not covering all cases

### LINKED ISSUE #382: Fix granting permissions on iOS not working in all cases
First reported by @iasiu in the customer project, then reported independently [here](https://github.com/leancodepl/patrol/issues/354#issuecomment-1260475603).

### PR DESCRIPTION
**Pull request by bartekpacia**
fix #382 

> Take this and drink from it: this is the cup of my blood.

### CODE REVIEW

File: AutomatorServer/ios/AutomatorServerUITests/PatrolAutomation.swift [hunk 1]
```diff
@@ -160,24 +160,33 @@ class PatrolAutomation {
   func allowPermissionWhileUsingApp() {
     runAction("allowing while using app") {
       let systemAlerts = self.springboard.alerts
-      let okButton = systemAlerts.buttons["OK"]
-      if okButton.exists {
-        okButton.tap()
-      }
+      let labels = ["OK", "Allow", "Allow While Using App"]
```
Comment (iasiu) [inline AutomatorServer/ios/AutomatorServerUITests/PatrolAutomation.swift:163]: Shouldn't `"Allow While Using App"` be first?

**Review by iasiu — APPROVED** [review]

File: AutomatorServer/ios/AutomatorServerUITests/PatrolAutomation.swift (hunk 1 above)
Comment (bartekpacia) [reply AutomatorServer/ios/AutomatorServerUITests/PatrolAutomation.swift:163]: It doesn't matter.
