### PR TITLE
fix trying to run tests which failed to build

### LINKED ISSUE #610: Don't run the test if it failed to build
Running a test has 2 parts: building and running. Currently, when building fails, patrol_cli still proceeds with running, which is wrong behavior.

This should be fixe.d

### PR DESCRIPTION
**Pull request by bartekpacia**
Fixes #610

### CODE REVIEW

File: packages/patrol_cli/test/features/drive/test_runner_test.dart [hunk 1]
```diff
@@ -31,12 +31,22 @@ void main() {
...
   group('TestRunner', () {
-    group('addDevice()', () {
-      setUp(() {
-        testRunner.builder = (_, __) => delay();
-        testRunner.executor = (_, __) => delay();
+    setUp(() {
+      testRunner.builder = (_, __) => delay();
+      testRunner.executor = (_, __) => delay();
+    });
+    group('set repeats', () {
```
Comment (shilangyu) [inline packages/patrol_cli/test/features/drive/test_runner_test.dart:38]: newline?

**Review by shilangyu — APPROVED** [review]

File: packages/patrol_cli/test/features/drive/test_runner_test.dart (hunk 1 above)
Comment (bartekpacia) [reply packages/patrol_cli/test/features/drive/test_runner_test.dart:38]: yup

thanks
