### PR TITLE
Change default analytics to opt out

### LINKED ISSUE #2475: Null check exception when running `patrol doctor`
When I run `patrol doctor` after installing the CLI, I get the following output:

```
Patrol doctor:
Patrol CLI version: 3.4.1
Flutter command: flutter 
  Flutter 3.27.1 • channel stable
Android: 
• Program adb found in /Users/admin/Library/Android/sdk/platform-tools/adb
• Env var $ANDROID_HOME is not set. (See the link: https://developer.android.com/tools/variables#set)
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
Unhandled exception:
Null check operator used on a null value
#0      PatrolCommand.flutterCommand (package:patrol_cli/src/runner/patrol_command.dart:241:30)
#1      DoctorCommand._printFlutterInfo (package:patrol_cli/src/commands/doctor.dart:49:17)
#2      DoctorCommand.run (package:patrol_cli/src/commands/doctor.dart:30:5)
#3      PatrolCommandRunner._runDoctor (package:patrol_cli/src/runner/patrol_command_runner.dart:408:57)
#4      PatrolCommandRunner._handleFirstRun (package:patrol_cli/src/runner/patrol_command_runner.dart:378:7)
#5      PatrolCommandRunner.run (package:patrol_cli/src/runner/patrol_command_runner.dart:300:7)
#6      patrolCommandRunner (package:patrol_cli/src/runner/patrol_command_runner.dart:71:33)
#7      main (file:///Users/admin/.pub-cache/hosted/pub.dev/patrol_cli-3.4.1/bin/main.dart:6:26)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

### PR DESCRIPTION
**Pull request by pdenert**
Add option to set `PATROL_ANALYTICS_ENABLED` environment.
Now analytics:
1. If PATROL_ANALYTICS_ENABLED is setup - use this variable value
2. If PATROL_ANALYTICS_ENABLED is not setup, but file $Home\.config\patrol_cli\analytics.json exist - take value from this file
3. Enable analytics by default

Should also fix #2475

### CODE REVIEW

File: packages/patrol_cli/lib/src/analytics/analytics.dart [hunk 1]
```diff
@@ -67,8 +70,15 @@ class Analytics {
...
+    /// use it to determine if the command should be sent.
+    /// If not set, use the value from the config file.
+    final enabled = _config?.enabled ?? true;
+    if (_envAnalyticsEnabled != null) {
+      if (!_envAnalyticsEnabled) {
+        return false;
+      }
+    } else if (!enabled) {
       return false;
     }
```
Comment (piotruela) [inline packages/patrol_cli/lib/src/analytics/analytics.dart:83]: How about:
```suggestion
    return _envAnalyticsEnabled ?? _config?.enabled ?? true;
```

File: packages/patrol_cli/lib/src/runner/patrol_command_runner.dart [hunk 2]
```diff
@@ -380,24 +397,16 @@ Ask questions, get support at https://github.com/leancodepl/patrol/discussions''
...
-    );
-    _analytics.enabled = analyticsEnabled;
-    if (analyticsEnabled) {
+    _logger.info(_helloPatrol);
+
+    /// If the environment variable `PATROL_ANALYTICS_ENABLED` is set,
+    /// use it to determine if the command should be sent.
+    /// If not, analytics will be enabled by default.
+    final patrolAnalyticsEnabled =
+        p.Platform.environment['PATROL_ANALYTICS_ENABLED'];
```
Comment (piotruela) [inline packages/patrol_cli/lib/src/runner/patrol_command_runner.dart:406]: I would put `PATROL_ANALYTICS_ENABLED` into a const variable to prevent misspelling.

File: packages/patrol_cli/lib/src/analytics/analytics.dart (hunk 1 above)
Comment (pdenert) [reply packages/patrol_cli/lib/src/analytics/analytics.dart:83]: We don't want return true here. Only return false, when we don't want to send analytics. Otherwise we just proceed

File: packages/patrol_cli/CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,8 @@
+## Unreleased
+
+- Add `PATROL_ANALYTICS_ENABLED` environment variable to disable analytics.
+- Enable analytics by default.
```
Comment (piotruela) [inline packages/patrol_cli/CHANGELOG.md:4]: Add a PR number (#2483) as we did for the previous records

**Review by piotruela — APPROVED** [review]
